name: sprint-12
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v4
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: go build -v ./...
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v4
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test  
      - name: Vet
        run: |
          go vet ./... 
  deploy:
    needs: test
    name: Push to Docker Hub
    runs-on: ubuntu-latest  
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ibragimf19/sprint-12

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}     

